### PR TITLE
Statuses filtered correctly for UI

### LINKED ISSUE #38: Initial list of available statuses keys is wrong
### Problem 
Initial list of available statuses keys is not filtered correctly, which produces incorrect behavior on client.

### Bugs because of this
1. The "All" filter for the Bookings list does not show all bookings. Rather, it remains blank until I click on a status filter.

If I visit "Scheduled", which has two bookings, the list will show both. If I go back to "All", it will now show the two scheduled bookings, but not any bookings with any other status.

2. When I am on the Bookings List view and I add a new booking manually, the Nedit booking modal closes, the status filters show one booking increasing for the status I selected, but the list does not update to show the booking I just created.

3. Screen options changes are applied when I hit the Apply button, but once I refresh the page, the screen options changes I made are not saved, and all statuses are selected again.

### Steps to reproduce
- Create some `in_cart` bookings via wizard
- Go to bookings page, observe bug 1.
- Create booking via editor, observe bug 2.
- Open screen options change it, press save.
- Refresh page, open screen options again, observe bug 3.

### Reason
Initial list of available statuses keys is not filtered correctly.

### Solution
Filter statuses keys correctly.

### PR DESCRIPTION
**Pull request by romalytvynenko**
fixes #38

### CODE REVIEW

File: src/Handlers/BookingsStateStatusesHandler.php [hunk 1]
```diff
@@ -217,14 +213,28 @@ protected function _getScreenStatuses($key, $defaultStatuses = [])
...
         if (!$screenOptions) {
-            return $this->_normalizeArray($defaultStatuses);
+            return $this->_getVisibleStatuses($defaultStatuses);
         }
-        $screenOptions = json_decode($screenOptions);
 
-        $statuses = $this->_trigger('eddbk_bookings_visible_statuses', [
-            'statuses' => $screenOptions,
-        ])->getParam('statuses');
+        $screenOptions = json_decode($screenOptions);
```
Comment (XedinUnknown) [inline src/Handlers/BookingsStateStatusesHandler.php]: Are there going to me multiple cases where `_getScreenStatuses()` needs to be called with different keys? If not, why not abstract retrieval of the user options, or better - the whole process of retrieving screen options?

**Review by XedinUnknown — CHANGES_REQUESTED** [review]

**Review by XedinUnknown — APPROVED** [review]
